spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/[DB name]
    username: [user id]
    password: [user password]
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create