spring:
  cloud:
    aws:
      credentials:
        access-key: ENC(Z7jweLMkcE9Kntpu6fYBB2iKajCn832xGqnmuZ8gX3w=)
        secret-key: ENC(tIuKb1AmKKAHh6VdMbNbnJ2FEipMM9PwdniGLOhdmwhQGQ07DQy4PQ8DfuqeFRFFxnRZnJ3eRjA=)
      region:
        static: ap-northeast-2
      s3:
        bucket: aws-shopping-teamsparta

  jasypt:
    encryptor:
      password: ${JASYPT_ENCRYPTOR_PASSWORD}